---
name: update go-github version

"on":
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  pull_request:
    uses: xorima/reusable-workflows/.github/workflows/go-github-renovate-update.yaml
